version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    labels:
      - dependencies
      - bundler
      - automated pr
    target-branch: qa
    reviewers:
      - hortongn
    assignees:
      - hortongn

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    labels:
      - dependencies
      - github actions
      - automated pr
    target-branch: qa
    reviewers:
      - hortongn
    assignees:
      - hortongn